apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.common.name }}
type: Opaque
data:
  {{- if .Values.common.secrets}}
  {{- range $key, $val := .Values.common.secrets }}
  {{ $key }}: {{ $val |b64enc  }}
  {{- end }}
  {{- end }}
{{/*  ks.p12: {{ .Values.secret.keyStore }}*/}}
{{/*  ks.secret: {{ .Values.secret.keyStorePAss | b64enc }}*/}}
