apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.common.name }}
  ports:
    - name: {{ .Values.common.name }}-port
      protocol: TCP
      port: 8080
      targetPort: message
  type: ClusterIP